FichaOnline/FichaOnline/Models/Ficha.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Ficha()
        {
            this.Peculiaridades = new HashSet<Peculiaridade>();
            this.PropriedadesRiquezasItensArmas = new HashSet<PropriedadeRiquezaItemArma>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Classe { get; set; }
        public string Raca { get; set; }
        public int Adre { get; set; }
        public int Ataq { get; set; }
        public int Defe { get; set; }
        public int Dest { get; set; }
        public int Forc { get; set; }
        public int Inte { get; set; }
        public int Resi { get; set; }
        public int Sabe { get; set; }
        public int Velo { get; set; }
        public int Vital { get; set; }
        public int Sorte { get; set; }
        public string Nota { get; set; }
        public int Experiencia { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> MestreId { get; set; }
        public int Pontos { get; set; }
        public int PtsPeculiaridades { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Peculiaridade> Peculiaridades { get; set; }
        public virtual ICollection<PropriedadeRiquezaItemArma> PropriedadesRiquezasItensArmas { get; set; }
    }
}

FichaOnline/FichaOnline/Controllers/FichaController.cs
using FichaOnline.Models;
using FichaOnline.Models.DAO;
using FichaOnline.Models.Facade;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaOnline.Controllers
{
    public class FichaController : Controller
    {
        public ActionResult Minhas()
        {
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View(new FichaDao().ListarPorUsuarioId(((Usuario)Session["usuario"]).Id));
        }

        public ActionResult Outras()
        {
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View(new FichaDao().ListarPorMestreId(((Usuario)Session["usuario"]).Id));
        }

        public ActionResult Nova()
        {
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View();
        }

        [HttpPost]
        public ActionResult Nova(FichaFacade ficha, int Nivel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var totalPts = (Nivel - 2.5) * 9;
                    var totalPtsPec = Math.Floor(Nivel - 2.5) * 10;
                    var pts = totalPts - (ficha.Adre + ficha.Ataq + ficha.Defe + ficha.Dest + ficha.Forc + ficha.Inte + ficha.Resi + ficha.Sabe + ficha.Velo);
                    ficha.Pontos = Convert.ToInt32(Math.Floor(pts));
                    ficha.PtsPeculiaridades = Convert.ToInt32(totalPtsPec);
                    var usuarioId = ((Usuario)Session["usuario"]).Id;
                    ficha.Ficha.UsuarioId = usuarioId;
                    if (ficha.Mestre != null) ficha.Ficha.MestreId = new UsuarioDao().SelecionarPorEmail(ficha.Mestre.Split(',')[1].Trim()).Id;
                    new FichaDao().Inserir(ficha.Ficha);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A Ficha " + ficha.Nome + " foi criada com sucesso!", "success");
                    return RedirectToAction("Minhas");
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar cadastrar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    if (Session["usuario"] == null)
                        return RedirectToAction("Entrar", "Entrada");
                    return View();
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View();
        }

        public ActionResult Ver(int id)
        {
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View(new FichaDao().SelecionarPorId(id));
        }

        public ActionResult Editar(int id)
        {
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            Session["autorizado"] = false;
            var ficha = new FichaDao().SelecionarPorId(id);
            var mestre = new UsuarioDao().SelecionarPorId(ficha.MestreId);
            var jogador = new UsuarioDao().SelecionarPorId(ficha.UsuarioId);
            var fichafac = new FichaFacade(ficha);
            if (mestre != null) fichafac.Mestre = mestre.Nome + ", " + mestre.Email;
            fichafac.Jogador = jogador.Nome + ", " + jogador.Email;
            if (ficha.MestreId == ((Usuario)Session["usuario"]).Id) Session["autorizado"] = true;
            return View(fichafac);
        }

        [HttpPost]
        public ActionResult Editar(FichaFacade ficha, int Id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var jogadorId = new UsuarioDao().SelecionarPorEmail(ficha.Jogador.Split(',')[1].Trim()).Id;
                    if (ficha.Mestre != null) ficha.Ficha.MestreId = new UsuarioDao().SelecionarPorEmail(ficha.Mestre.Split(',')[1].Trim()).Id;
                    ficha.Ficha.Id = Id;
                    ficha.Ficha.UsuarioId = jogadorId;
                    new FichaDao().Atualizar(ficha.Ficha);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A Ficha " + ficha.Nome + " foi editada com sucesso!", "success");
                    return View(ficha);
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar editar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    if (Session["usuario"] == null)
                        return RedirectToAction("Entrar", "Entrada");
                    return View(ficha);
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            if (Session["usuario"] == null)
                return RedirectToAction("Entrar", "Entrada");
            return View();
        }

        public ActionResult Excluir(int id)
        {
            try
            {
                var ficha = new FichaDao().SelecionarPorId(id);
                if (ficha.Pontos > 0) ficha.Pontos = ficha.Pontos * (-1);
                else ficha.Pontos = -1000;
                new FichaDao().Atualizar(ficha);
                Session["alert"] = UtilController.RenderAlert("Sucesso!", "A Ficha " + ficha.Nome + " foi excluída com sucesso!", "success");
                return RedirectToAction("Minhas");
            }
            catch (Exception ex)
            {
                Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar excluir. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                if (Session["usuario"] == null)
                    return RedirectToAction("Entrar", "Entrada");
                return RedirectToAction("Minhas");
            }
        }

        public JsonResult AutocompleteClasse(string term)
        {
            return Json(new FichaDao().SelecionarNomesClasses(term), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AutocompleteRaca(string term)
        {
            return Json(new FichaDao().SelecionarNomesRacas(term), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AutocompleteJogador(string term)
        {
            return AutocompleteMestre(term);
        }

        public JsonResult AutocompleteMestre(string term)
        {
            return Json(new UsuarioDao().SelecionarMestres(term), JsonRequestBehavior.AllowGet);
        }
    }
}

FichaOnline/FichaOnline/Controllers/PRIAController.cs
using FichaOnline.Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FichaOnline.Models.Facade;
using FichaOnline.Models;

namespace FichaOnline.Controllers
{
    public class PRIAController : Controller
    {
        public ActionResult Listar(int fichaId, string tipo)
        {
            ViewBag.Tipo = tipo;
            return View(new PRIADao().ListarPorFichaIdETipo(fichaId, tipo));
        }

        public ActionResult Administrar(int fichaId, string tipo)
        {
            ViewBag.Tipo = tipo;
            ViewBag.IdTipo = new object[] { fichaId, tipo };
            if (fichaId == 0) return View(new PRIADao().ListarPorTipo(tipo));
            else return View(new PRIADao().ListarPorFichaIdETipo(fichaId, tipo));
        }

        public ActionResult Editar(int id)
        {
            return View(new PRIAFacade(new PRIADao().SelecionarPorId(id)));
        }

        [HttpPost]
        public ActionResult Editar(PRIAFacade pria, int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    pria.PropriedadeRiquezaItemArma.Id = id;
                    new PRIADao().Atualizar(pria.PropriedadeRiquezaItemArma);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A " + ((pria.Tipo == "pr/ri") ? "Propriedade/Riqueza " + pria.Descricao : "Item/Arma " + pria.Nome) + " foi editada com sucesso!", "success");
                    return View(pria);
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar editar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    return View();
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            return View();
        }

        public ActionResult Criar(int id, string tipo)
        {
            return View(new PRIAFacade(new PropriedadeRiquezaItemArma { FichaId = id, Tipo = tipo }));
        }

        [HttpPost]
        public ActionResult Criar(PRIAFacade pria)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    new PRIADao().Inserir(pria.PropriedadeRiquezaItemArma);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A  " + pria.Nome + " foi criada com sucesso!", "success");
                    return View(new PRIAFacade(new PropriedadeRiquezaItemArma { FichaId = pria.FichaId, Tipo = pria.Tipo }));
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar criar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    return View(new PRIAFacade(new PropriedadeRiquezaItemArma { FichaId = pria.FichaId, Tipo = pria.Tipo }));
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            return View(new PRIAFacade(new PropriedadeRiquezaItemArma { FichaId = pria.FichaId, Tipo = pria.Tipo }));
        }

        public JsonResult AutocompletePropriedadeRiqueza(string term)
        {
            return Json(new PRIADao().SelecionarDescricoesPropriedadeRiqueza(term, "pr/ri"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AutocompleteItemArma(string term)
        {
            return Json(new PRIADao().SelecionarSubtipo(term, "it/ar"), JsonRequestBehavior.AllowGet);
        }
    }
}

FichaOnline/FichaOnline/Controllers/PeculiaridadeController.cs
using FichaOnline.Models;
using FichaOnline.Models.DAO;
using FichaOnline.Models.Facade;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaOnline.Controllers
{
    public class PeculiaridadeController : Controller
    {
        public ActionResult Listar(int fichaId, string tipo)
        {
            return View(new PeculiaridadeDao().ListarPorFichaIdETipo(fichaId, tipo));
        }

        public ActionResult Administrar(int fichaId, string tipo)
        {
            ViewBag.IdTipo = new object[] { fichaId, tipo };
            if (fichaId == 0) return View(new PeculiaridadeDao().ListarPorTipo(tipo));
            else return View(new PeculiaridadeDao().ListarPorFichaIdETipo(fichaId, tipo));
        }

        public ActionResult Editar(int id)
        {
            return View(new PeculFacade(new PeculiaridadeDao().SelecionarPorId(id)));
        }

        [HttpPost]
        public ActionResult Editar(PeculFacade pec, int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    pec.Peculiaridade.Id = id;
                    new PeculiaridadeDao().Atualizar(pec.Peculiaridade);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A Peculiaridade " + pec.Nome + " foi editada com sucesso!", "success");
                    return View(pec);
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar editar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    return View();
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            return View();
        }

        public ActionResult Criar(int id, string tipo)
        {
            return View(new PeculFacade(new Peculiaridade { FichaId = id, Tipo = tipo }));
        }

        [HttpPost]
        public ActionResult Criar(PeculFacade pec)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    new PeculiaridadeDao().Inserir(pec.Peculiaridade);
                    Session["alert"] = UtilController.RenderAlert("Sucesso!", "A Peculiaridade " + pec.Nome + " foi criada com sucesso!", "success");
                    return View(new PeculFacade(new Peculiaridade { FichaId = pec.FichaId, Tipo = pec.Tipo }));
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar criar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    return View(new PeculFacade(new Peculiaridade { FichaId = pec.FichaId, Tipo = pec.Tipo }));
                }
            }
            Session["alert"] = UtilController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            return View(new PeculFacade(new Peculiaridade { FichaId = pec.FichaId, Tipo = pec.Tipo }));
        }

        public JsonResult AutocompleteCapacidade(string term)
        {
            return Json(new PeculiaridadeDao().SelecionarNomesPeculiaridades(term,"cap"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AutocompletePericia(string term)
        {
            return Json(new PeculiaridadeDao().SelecionarNomesPeculiaridades(term, "per"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult AutocompleteDesvantagem(string term)
        {
            return Json(new PeculiaridadeDao().SelecionarNomesPeculiaridades(term, "des"), JsonRequestBehavior.AllowGet);
        }
    }
}

FichaOnline/FichaOnline/Views/Ficha/Editar.cshtml
@model FichaOnline.Models.Facade.FichaFacade
@{
    ViewBag.Background = "transparent";

    var titulo = "Uma das minhas fichas.";
    if (((FichaOnline.Models.Usuario)Session["usuario"]).Id != Model.Ficha.UsuarioId)
    {
        var jogador = new FichaOnline.Models.DAO.UsuarioDao().SelecionarPorId(Model.Ficha.UsuarioId);
        titulo = "Ficha do jogador " + jogador.Nome + " (" + jogador.Email + ")";
    }
    int nivel = (Model.Adre + Model.Ataq + Model.Defe + Model.Dest + Model.Forc + Model.Inte + Model.Resi + Model.Sabe + Model.Velo) / 9;
    var PV = Model.Resi * 10;
    var nota = "NÍVEL: " + nivel.ToString("00") + "\n"
              + "PV: " + PV.ToString("000") + "\n"
              + "\n" + Model.Nota;
              
    var nome = ((FichaOnline.Models.Usuario)Session["usuario"]).Nome;
    var email = ((FichaOnline.Models.Usuario)Session["usuario"]).Email;
}
<script>
    @Html.Raw(Session["alert"])
    @{ Session.Remove("alert"); }

    $(function () {
        $('#Classe').autocomplete({
            source: '@Url.Action("AutocompleteClasse")'
        });

        $('#Raca').autocomplete({
            source: '@Url.Action("AutocompleteRaca")'
        });

        $('#Jogador').autocomplete({
            source: '@Url.Action("AutocompleteJogador")'
        });

        $('#Mestre').autocomplete({
            source: '@Url.Action("AutocompleteMestre")'
        });
    });
</script>
@if (Session["autorizado"].ToString() == "False")
{
    <script>
        $(function () {
            $('#Idade').attr('readonly', 'true');
            $('#Classe').attr('readonly', 'true');
            $('#Raca').attr('readonly', 'true');
            $('#Sorte').attr('readonly', 'true');
            $('#Vital').attr('readonly', 'true');
            $('#Nota').attr('readonly', 'true');
        });
    </script>
    if (Model.Pontos == 0)
    {
        <script>
            $(function () {
                $.each($('.teste'), function () {
                    $(this).attr('readonly', 'true');
                });
            });
        </script>
    }
    if (Model.Mestre != nome + ", " + email)
    {
        <script>
            $(function () {
                $('#Pontos').attr('readonly', 'true');
            });
        </script>
    }
}
<div class="centralizar">
    <div class="borda-cadastro borda-nova">
        <div class="conteudo-cadastro terrain scrollable conteudo-nova">
            <fieldset>
                <legend class="text-whitesmoke">@titulo</legend>
                @using (Html.BeginForm())
                {
                    <div id="summary">
                        @Html.ValidationSummary("Preencha os campos obrigatórios!")
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-2">
                            <label class="control-label">
                                <span class="text-form">Pts a Incluir: </span>
                            </label>
                            <input type="hidden" id="pts" value="@Model.Pontos" />
                            @Html.TextBoxFor(model => model.Pontos, new { type = "number", @class = "form-control" })
                        </div>
                        <div class="col-md-5">
                            <label class="control-label">
                                <span class="text-form">Jogador: </span>
                            </label>
                            @Html.TextBoxFor(model => model.Jogador, new { @class = "form-control" })
                        </div>
                        <div class="col-md-5">
                            <label class="control-label">
                                <span class="text-form">Mestre: </span> @Html.ValidationMessageFor(model => model.Mestre)
                            </label>
                            @Html.TextBoxFor(model => model.Mestre, new { @class = "form-control" })
                        </div>
                    </div>
                    <hr class="col-md-12" />
                    <div class="col-md-2">
                        <div class="col-md-12 no-padding"><label class="text-form">ADRE</label> @Html.TextBoxFor(model => model.Adre, new { min = @Model.Adre, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">ATAQ</label> @Html.TextBoxFor(model => model.Ataq, new { min = @Model.Ataq, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">DEFE</label> @Html.TextBoxFor(model => model.Defe, new { min = @Model.Defe, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">DEST</label> @Html.TextBoxFor(model => model.Dest, new { min = @Model.Dest, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">FORÇ</label> @Html.TextBoxFor(model => model.Forc, new { min = @Model.Forc, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">INTE</label> @Html.TextBoxFor(model => model.Inte, new { min = @Model.Inte, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">RESI</label> @Html.TextBoxFor(model => model.Resi, new { min = @Model.Resi, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">SABE</label> @Html.TextBoxFor(model => model.Sabe, new { min = @Model.Sabe, type = "number", @class = "form-control teste" })</div>
                        <div class="col-md-12 no-padding"><label class="text-form">VELO</label> @Html.TextBoxFor(model => model.Velo, new { min = @Model.Velo, type = "number", @class = "form-control teste" })</div>
                    </div>
                    <div class="col-md-10">
                        <div class="col-md-3">
                            <div class="col-md-12 no-padding"><label class="text-form">Vital</label> @Html.TextBoxFor(model => model.Vital, new { type = "number", @class = "form-control" })</div>
                            <div class="col-md-12 no-padding"><label class="text-form">Sorte</label> @Html.TextBoxFor(model => model.Sorte, new { type = "number", @class = "form-control" })</div>
                        </div>
                        <div class="col-md-9">
                            <div class="col-md-8"><label class="text-form">Nome:</label> @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })</div>
                            <div class="col-md-4"><label class="text-form">Idade:</label> @Html.TextBoxFor(model => model.Idade, new { type = "number", @class = "form-control" })</div>
                            <div class="col-md-8"><label class="text-form">Classe:</label> @Html.TextBoxFor(model => model.Classe, new { @class = "form-control" })</div>
                            <div class="col-md-4"><label class="text-form">Raça:</label> @Html.TextBoxFor(model => model.Raca, new { @class = "form-control" })</div>
                        </div>
                        <div class="col-md-6">
                            <strong class="text-high-high">Capacidades</strong>
                            <hr class="no-margin" />
                            <div class="col-md-12 scrollable ficha-bloco">
                                @if (Session["autorizado"].ToString() == "False")
                                {
                                    @Html.Action("Listar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "cap" })
                                }
                                else
                                {
                                    @Html.Action("Administrar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "cap" })
                                }
                            </div>
                        </div>
                        <div class="col-md-6">
                            <strong class="text-high-high">Perícias</strong>
                            <hr class="no-margin" />
                            <div class="col-md-12 scrollable ficha-bloco">
                                @if (Session["autorizado"].ToString() == "False")
                                {
                                    @Html.Action("Listar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "per" })
                                }
                                else
                                {
                                    @Html.Action("Administrar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "per" })
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-7 no-padding">
                            <div class="col-md-12 no-padding">
                                <strong class="text-high-high">Propriedades/Riquezas</strong>
                                <hr class="no-margin" />
                                <div class="col-md-12 scrollable ficha-bloco">
                                    @if (Session["autorizado"].ToString() == "False")
                                    {
                                        @Html.Action("Listar", "PRIA", new { fichaId = Model.Ficha.Id, tipo = "pr/ri" })
                                    }
                                    else
                                    {
                                        @Html.Action("Administrar", "PRIA", new { fichaId = Model.Ficha.Id, tipo = "pr/ri" })
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <strong class="text-high-high">Desvantagens</strong>
                            <hr class="no-margin" />
                            <div class="col-md-12 scrollable">
                                @if (Session["autorizado"].ToString() == "False")
                                {
                                    @Html.Action("Listar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "des" })
                                }
                                else
                                {
                                    @Html.Action("Administrar", "Peculiaridade", new { fichaId = Model.Ficha.Id, tipo = "des" })
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-7 no-padding">
                            <div class="col-md-12 no-padding">
                                <strong class="text-high-high">Itens/Armas</strong>
                                <hr class="no-margin" />
                                <div class="col-md-12 scrollable ficha-bloco">
                                    @if (Session["autorizado"].ToString() == "False")
                                    {
                                        @Html.Action("Listar", "PRIA", new { fichaId = Model.Ficha.Id, tipo = "it/ar" })
                                    }
                                    else
                                    {
                                        @Html.Action("Administrar", "PRIA", new { fichaId = Model.Ficha.Id, tipo = "it/ar" })
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <strong class="text-high-high">Anotações do Mestre</strong>
                            <hr class="no-margin" />
                            @Html.TextAreaFor(model => model.Nota, new { rows = "10", @class = "form-control col-md-12" })
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-7 no-padding">
                            <div class="col-md-12 no-padding">
                                <strong class="text-high-high">Pontos de Experiência</strong>
                                <hr class="no-margin" />
                            </div>
                        </div>
                        <div class="col-md-5">
                            <strong class="text-high-high">Ações</strong>
                            <hr class="no-margin" />
                            <input type="submit" class="btn btn-primary btn-block" value="Salvar" onclick="$('#summary').attr('class', 'field-validation-error')" />
                            <hr />
                            <a href="/Ficha/Minhas" class="btn btn-xs btn-danger btn-block">Cancelar</a>
                        </div>
                    </div>
                }
            </fieldset>
        </div>
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

FichaOnline/FichaOnline/Views/Ficha/Excluir.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Excluindo...</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>