FichaOnline/FichaOnline/Controllers/DueloController.cs
using FichaOnline.Models;
using FichaOnline.Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FichaOnline.Controllers
{
    public class DueloController : Controller
    {
        public ActionResult Listar(int id)
        {
            try
            {
                List<Ficha> fichas = new List<Ficha>();
                fichas.AddRange(new FichaDao().ListarPorUsuarioId(id));
                fichas.AddRange(new FichaDao().ListarPorMestreId(id));
                return View(fichas);
            }
            catch (Exception ex)
            {
                Session["alert"] = UtilController.RenderAlert("Erro!", "Erro ao tentar listar fichas. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                if (Session["usuario"] == null)
                    return RedirectToAction("Entrar", "Entrada");
                return View();
            }
        }

        [HttpPost]
        public ActionResult Duelando(int[] fichasId)
        {
            if (fichasId.Count() >= 2) 
            {
                List<Ficha> fichas = new List<Ficha>();
                foreach (int id in fichasId)
                    fichas.Add(new FichaDao().SelecionarPorId(id));
                return View(fichas);
            }
            else
            {
                Session["alert"] = UtilController.RenderAlert("Ops!", "Selecione pelo menos 2 fichas!", "warning");
                if (Session["usuario"] == null)
                    return RedirectToAction("Entrar", "Entrada");
                return View();
            }
        }
    }
}

FichaOnline/FichaOnline/Views/Duelo/Duelando.cshtml
@model List<FichaOnline.Models.Ficha>
@{
    ViewBag.Background = "transparent";
}

FichaOnline/FichaOnline/Views/Duelo/Listar.cshtml
@model List<FichaOnline.Models.Ficha>
@{
    ViewBag.Background = "transparent";
    var myId = ((FichaOnline.Models.Usuario)Session["usuario"]).Id;
}

@using (Html.BeginForm("Duelando", "Duelo", FormMethod.Post, new { @class = "scrollable" }))
{
    var cont = 0;
    foreach (var f in Model)
    {
        int nivel = (f.Adre + f.Ataq + f.Defe + f.Dest + f.Forc + f.Inte + f.Resi + f.Sabe + f.Velo) / 9;
        var PV = f.Resi * 10;
        if (f.UsuarioId == myId)
        {
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 terrain item-small">
                <div class="text-whitesmoke text-high form-group"><strong class="control-label">@f.Nome</strong> <input class="chbx checkbox-inline" type="checkbox" name="fichasId" value="@f.Id" /></div>
                <div class="col-md-8 no-padding"><label class="text-form">Raça</label> - <span class="text-high-high">@f.Raca</span></div>
                <div class="col-md-4 no-padding"><label class="text-form">Idade</label> - <span class="text-high-high">@f.Idade.ToString("00")</span></div>
                <div class="col-md-8 no-padding"><label class="text-form">NÍVEL</label> - <span class="text-high-high">@nivel.ToString("00")</span></div>
                <div class="col-md-4 no-padding"><label class="text-form">PV</label> - <span class="text-high-high">@PV</span></div>
            </div>
        }
        if (f.MestreId == myId && f.UsuarioId != myId)
        {
            if (cont == 0)
            {
                <hr class="col-lg-12 col-md-12 col-sm-12 col-xs-12" />
                cont++;
            }
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 terrain item-small">
                <div class="text-whitesmoke text-high form-group"><strong class="control-label">@f.Nome</strong> <input class="chbx checkbox-inline" type="checkbox" name="fichasId" value="@f.Id" /></div>
                <div class="col-md-8 no-padding"><label class="text-form">Raça</label> - <span class="text-high-high">@f.Raca</span></div>
                <div class="col-md-4 no-padding"><label class="text-form">Idade</label> - <span class="text-high-high">@f.Idade.ToString("00")</span></div>
                <div class="col-md-8 no-padding"><label class="text-form">NÍVEL</label> - <span class="text-high-high">@nivel.ToString("00")</span></div>
                <div class="col-md-4 no-padding"><label class="text-form">PV</label> - <span class="text-high-high">@PV</span></div>
            </div>
        }
    }
    <hr class="col-lg-12 col-md-12 col-sm-12 col-xs-12" />
    <input type="submit" class="btn btn-success btn-block" value="Iniciar!" />
}       